version: '3.8'

networks:
  memory-partner-network:

services:

  memoryPartnerDb:
    container_name:  memoryPartnerDb
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - memory-partner-volume:/var/lib/mysql:rw
      - ./memoryPartnerDb:/docker-entrypoint-initdb.d/
    networks:
      - memory-partner-network

  server:
    container_name: server
    # depends_on:
    #   - memoryPartnerDb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - memory-partner-network
    
  client:
    container_name: client
    # depends_on: 
      # - server
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - memory-partner-network

volumes: 
  memory-partner-volume: